# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/camera/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/sony/camera

PRODUCT_COPY_FILES += \
    vendor/sony/camera/proprietary/system/etc/permissions/com.sony.device.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.sony.device.xml \
    vendor/sony/camera/proprietary/system/etc/permissions/com.sonyericsson.idd.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.sonyericsson.idd.xml \
    vendor/sony/camera/proprietary/system/etc/permissions/com.sonymobile.getmore.api.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.sonymobile.getmore.api.xml \
    vendor/sony/camera/proprietary/system/etc/permissions/com.sonymobile.securedatamanager.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.sonymobile.securedatamanager.xml \
    vendor/sony/camera/proprietary/system/etc/permissions/com.sonymobile.vibrationeffect.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/com.sonymobile.vibrationeffect.xml \
    vendor/sony/camera/proprietary/system/etc/permissions/platform-com.sonyericsson.android.camera.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/platform-com.sonyericsson.android.camera.xml \
    vendor/sony/camera/proprietary/system/etc/permissions/privapp-permissions-com.sonyericsson.android.camera.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-com.sonyericsson.android.camera.xml \
    vendor/sony/camera/proprietary/system/etc/permissions/privapp-permissions-com.sonymobile.addoncamera.portraitselfie.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-com.sonymobile.addoncamera.portraitselfie.xml \
    vendor/sony/camera/proprietary/system/etc/sysconfig/somc_internal_whitelist.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/sysconfig/somc_internal_whitelist.xml \
    vendor/sony/camera/proprietary/system/priv-app/com.sonymobile.addoncamera.portraitselfie/lib/arm/libarcsoft_beautyshot.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/com.sonymobile.addoncamera.portraitselfie/lib/arm/libarcsoft_beautyshot.so \
    vendor/sony/camera/proprietary/system/priv-app/com.sonymobile.addoncamera.portraitselfie/lib/arm/libarcsoft_picselfie_algorithm.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/com.sonymobile.addoncamera.portraitselfie/lib/arm/libarcsoft_picselfie_algorithm.so \
    vendor/sony/camera/proprietary/system/priv-app/com.sonymobile.addoncamera.portraitselfie/lib/arm/libbeauty_picselfie.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/com.sonymobile.addoncamera.portraitselfie/lib/arm/libbeauty_picselfie.so \
    vendor/sony/camera/proprietary/system/priv-app/com.sonymobile.addoncamera.portraitselfie/lib/arm/libmpbase.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/com.sonymobile.addoncamera.portraitselfie/lib/arm/libmpbase.so \
    vendor/sony/camera/proprietary/system/priv-app/com.sonymobile.addoncamera.portraitselfie/lib/arm/libpp.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/com.sonymobile.addoncamera.portraitselfie/lib/arm/libpp.so \
    vendor/sony/camera/proprietary/system/priv-app/com.sonymobile.addoncamera.portraitselfie/lib/arm64/libarcsoft_beautyshot.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/com.sonymobile.addoncamera.portraitselfie/lib/arm64/libarcsoft_beautyshot.so \
    vendor/sony/camera/proprietary/system/priv-app/com.sonymobile.addoncamera.portraitselfie/lib/arm64/libarcsoft_picselfie_algorithm.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/com.sonymobile.addoncamera.portraitselfie/lib/arm64/libarcsoft_picselfie_algorithm.so \
    vendor/sony/camera/proprietary/system/priv-app/com.sonymobile.addoncamera.portraitselfie/lib/arm64/libbeauty_picselfie.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/com.sonymobile.addoncamera.portraitselfie/lib/arm64/libbeauty_picselfie.so \
    vendor/sony/camera/proprietary/system/priv-app/com.sonymobile.addoncamera.portraitselfie/lib/arm64/libmpbase.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/com.sonymobile.addoncamera.portraitselfie/lib/arm64/libmpbase.so \
    vendor/sony/camera/proprietary/system/priv-app/com.sonymobile.addoncamera.portraitselfie/lib/arm64/libpp.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/com.sonymobile.addoncamera.portraitselfie/lib/arm64/libpp.so \
    vendor/sony/camera/proprietary/system/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libarcsoft_handsigns.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libarcsoft_handsigns.so \
    vendor/sony/camera/proprietary/system/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libc++_shared.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libc++_shared.so \
    vendor/sony/camera/proprietary/system/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libdetector.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libdetector.so \
    vendor/sony/camera/proprietary/system/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libhandsigns_jni.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libhandsigns_jni.so \
    vendor/sony/camera/proprietary/system/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libhta.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libhta.so \
    vendor/sony/camera/proprietary/system/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libimage_converter.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libimage_converter.so \
    vendor/sony/camera/proprietary/system/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libmpbase.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libmpbase.so \
    vendor/sony/camera/proprietary/system/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libSNPE.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libSNPE.so \
    vendor/sony/camera/proprietary/system/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libsnpe_adsp.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libsnpe_adsp.so \
    vendor/sony/camera/proprietary/system/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libsnpe_dsp_domains.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libsnpe_dsp_domains.so \
    vendor/sony/camera/proprietary/system/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libsnpe_dsp_domains_skel.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libsnpe_dsp_domains_skel.so \
    vendor/sony/camera/proprietary/system/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libsnpe_dsp_domains_v2.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libsnpe_dsp_domains_v2.so \
    vendor/sony/camera/proprietary/system/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libsnpe_dsp_skel.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libsnpe_dsp_skel.so \
    vendor/sony/camera/proprietary/system/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libsnpe_dsp_v65_domains_v2_skel.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libsnpe_dsp_v65_domains_v2_skel.so \
    vendor/sony/camera/proprietary/system/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libsnpe_dsp_v66_domains_v2_skel.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libsnpe_dsp_v66_domains_v2_skel.so \
    vendor/sony/camera/proprietary/system/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libsnpe-android.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libsnpe-android.so \
    vendor/sony/camera/proprietary/system/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libsymphony-cpu.so:$(TARGET_COPY_OUT_SYSTEM)/priv-app/SemcCameraUI-xxhdpi-release/lib/arm64/libsymphony-cpu.so

PRODUCT_PACKAGES += \
    ArtFilterCamera-xxhdpi-release \
    CameraPanorama-release \
    SemcCameraUI-xxhdpi-release \
    com.sonymobile.addoncamera.portraitselfie \
    com.sony.device \
    com.sonyericsson.idd_impl \
    com.sonymobile.getmore.api \
    com.sonymobile.securedatamanager_impl \
    com.sonymobile.vibrationeffect_impl
